CRITICAL - 2021-04-30 22:12:54 --> syntax error, unexpected token "=>"
#0 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#4 C:\xampp\htdocs\apica\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#5 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-04-30 22:13:16 --> syntax error, unexpected token "=>"
#0 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#4 C:\xampp\htdocs\apica\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#5 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-04-30 22:14:27 --> syntax error, unexpected token "=>"
#0 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#4 C:\xampp\htdocs\apica\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#5 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-04-30 22:15:40 --> syntax error, unexpected token "=>"
#0 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#4 C:\xampp\htdocs\apica\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#5 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-04-30 22:33:33 --> Undefined variable $ajc_id
#0 C:\xampp\htdocs\apica\app\Controllers\TipoVehiculo.php(145): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 145)
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\TipoVehiculo->update('13')
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TipoVehiculo))
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-04-30 22:48:55 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\apica\system\Model.php(615): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\apica\system\Model.php(834): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\apica\app\Controllers\TipoFranquicia.php(135): CodeIgniter\Model->__call('getAjusteCentav...', Array)
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\TipoFranquicia->update('5')
#4 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TipoFranquicia))
#5 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-04-30 23:11:14 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\apica\system\Model.php(615): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\apica\system\Model.php(834): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\apica\app\Controllers\DatosPersonales.php(37): CodeIgniter\Model->__call('getUnDatosPerso...', Array)
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\DatosPersonales->show('17')
#4 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DatosPersonales))
#5 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-04-30 23:12:25 --> Undefined array key "dap_id"
#0 C:\xampp\htdocs\apica\app\Controllers\DatosPersonales.php(141): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 141)
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\DatosPersonales->update('17')
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DatosPersonales))
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-04-30 23:12:39 --> Attempt to read property "dap_id" on array
#0 C:\xampp\htdocs\apica\app\Controllers\DatosPersonales.php(141): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\xampp\\htdocs...', 141)
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\DatosPersonales->update('17')
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DatosPersonales))
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-04-30 23:13:01 --> json_decode(): Argument #1 ($json) must be of type string, array given
#0 C:\xampp\htdocs\apica\app\Controllers\DatosPersonales.php(140): json_decode(Array)
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\DatosPersonales->update('17')
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DatosPersonales))
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-04-30 23:13:46 --> json_decode(): Argument #1 ($json) must be of type string, array given
#0 C:\xampp\htdocs\apica\app\Controllers\DatosPersonales.php(141): json_decode(Array, true)
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\DatosPersonales->update('17')
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DatosPersonales))
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-04-30 23:25:29 --> Undefined array key "cui_id"
#0 C:\xampp\htdocs\apica\app\Controllers\DatosPersonales.php(144): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 144)
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\DatosPersonales->update('19')
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DatosPersonales))
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-04-30 23:26:36 --> syntax error, unexpected token "catch"
#0 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#4 C:\xampp\htdocs\apica\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#5 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-04-30 23:27:13 --> syntax error, unexpected token "catch"
#0 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#4 C:\xampp\htdocs\apica\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#5 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-04-30 23:27:16 --> syntax error, unexpected token "catch"
#0 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\apica\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#4 C:\xampp\htdocs\apica\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#5 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-04-30 23:28:24 --> Undefined array key "dap_segundonombre"
#0 C:\xampp\htdocs\apica\app\Controllers\DatosPersonales.php(153): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 153)
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\DatosPersonales->update('19')
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DatosPersonales))
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-04-30 23:57:30 --> Undefined variable $suario_model
#0 C:\xampp\htdocs\apica\app\Controllers\Usuario.php(132): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 132)
#1 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\Usuario->update('4')
#2 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
