ERROR - 2021-04-29 14:39:45 --> mysqli_sql_exception: Unknown table 'bdd_rapidito_carga_pesada.tbl_datospersonales' in C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-29 14:39:45 --> Unknown table 'bdd_rapidito_carga_pesada.tbl_datospersonales'
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-29 14:40:32 --> mysqli_sql_exception: Unknown table 'bdd_rapidito_carga_pesada.tbl_datospersonales' in C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-29 14:40:32 --> Unknown table 'bdd_rapidito_carga_pesada.tbl_datospersonales'
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-29 14:40:53 --> mysqli_sql_exception: Unknown column 'tbl_usuario.usu_id' in 'on clause' in C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-29 14:40:53 --> Unknown column 'tbl_usuario.usu_id' in 'on clause'
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-29 14:42:10 --> mysqli_sql_exception: Unknown column 'tbl_usuario.usu_id' in 'on clause' in C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-29 14:42:10 --> Unknown column 'tbl_usuario.usu_id' in 'on clause'
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-29 14:42:44 --> mysqli_sql_exception: Unknown column 'tbl_usuario.usu_id' in 'field list' in C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-29 14:42:44 --> Unknown column 'tbl_usuario.usu_id' in 'field list'
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-29 14:47:48 --> mysqli_sql_exception: Unknown table 'bdd_rapidito_carga_pesada.tbl_datospersonales' in C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-29 14:47:48 --> Unknown table 'bdd_rapidito_carga_pesada.tbl_datospersonales'
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-29 14:58:43 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `persona`, `tbl_datospersonales`.* as `persona2`
FROM `tbl_pedidocabecera`...' at line 1 in C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(17): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-29 14:58:43 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `persona`, `tbl_datospersonales`.* as `persona2`
FROM `tbl_pedidocabecera`...' at line 1
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(17): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-29 15:00:27 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `persona`, `tbl_datospersonales`.* as `persona2`
FROM `tbl_pedidocabecera`...' at line 1 in C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(17): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-29 15:00:27 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `persona`, `tbl_datospersonales`.* as `persona2`
FROM `tbl_pedidocabecera`...' at line 1
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(17): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-29 15:13:02 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `persona`, `tbl_datospersonales`.* as `conductor`
FROM `tbl_pedidocabecera...' at line 1 in C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(17): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-29 15:13:02 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `persona`, `tbl_datospersonales`.* as `conductor`
FROM `tbl_pedidocabecera...' at line 1
#0 C:\xampp\htdocs\apica\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT `tbl_ped...')
#1 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `tbl_ped...')
#2 C:\xampp\htdocs\apica\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `tbl_ped...')
#3 C:\xampp\htdocs\apica\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `tbl_ped...', Array, false)
#4 C:\xampp\htdocs\apica\app\Models\PedidoCabeceraModel.php(17): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\apica\app\Controllers\PedidoCabecera.php(17): App\Models\PedidoCabeceraModel->getreportehoy('2021-04-29')
#6 C:\xampp\htdocs\apica\system\CodeIgniter.php(936): App\Controllers\PedidoCabecera->reportehoy()
#7 C:\xampp\htdocs\apica\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PedidoCabecera))
#8 C:\xampp\htdocs\apica\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apica\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
